apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo:4.0.10
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"
        - name: MONGO_INITDB_DATABASE
          value: "admin"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
    

spec:
  selector:
    app: mongo-db
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32701
